# Children of Morta, with Flydigi Apex 2 in mind
game = "Children of Morta"
fps = 60 # How often to read/emit inputs

[mapping]
# Joy for some movement
JoyX = { action = "NegPos", keys = ["A", "D"], deadzone = 0.4 } # Move w/e
JoyY = { action = "NegPos", keys = ["W", "S"], deadzone = 0.4 } # Move n/s

# D-Pad for digital movement
PovLeft = "A" # Strafe Left
PovRight = "D" # Strafe Right
PovUp = "W" # Walk
PovDown = "S" # Retreat

# Triggers
BumperL = "Shift" # Special
ActionL = "Q" # First Divine Relic
TriggerL = "Ctrl" # Guardian's Rage

BumperR = "M2" # Secondary
ActionR = "E" # Second Divine Relic
TriggerR = "M1" # Attack

# Face Buttons
ActionA = "Space" # Dodge
ActionB = "F" # Interact
ActionH = "R" # Use charm
ActionV = "T" # Teleport / Talent
ActionC = "M" # Map
ActionD = "C" # Item Info

# Menu Buttons
MenuL = "Tab" # Menu stuff
MenuR = "Escape" # Options
