# Deep Rock Galactic, with Flydigi Apex 2 in mind
game = "Deep Rock Galactic"
fps = 60 # How often to read/emit inputs
flick180 = 4906 # Mouse units to move 180

[mapping]
# D-Pad
PovLeft = "A" # Strafe Left
PovRight = "D" # Strafe Right
PovUp = "W" # Walk
PovDown = "S" # Retreat

# Right Stick
CamX = "FlickX" # Turn
CamY = "FlickY" # Turn

# Rear Triggers
BumperL = "Ctrl" # Laser Pointer
ActionL = "Shift" # Sprint
ActionA = "Space" # Jump
ActionR = "E" # Interact
TriggerR = "M1" # Shoot
TriggerL = "M2" # Mine
BumperR = "G" # Grenade
ActionV = "C" # Molly
ActionC = "X" # Shout
ActionD = "V" # Salute

# Face Buttons
ActionH = "R" # Reload
ActionB = "F" # Flares

# Middle Buttons
MenuL = "Tab" # Map
MenuR = "Escape" # Pause

# Under Buttons
PaddleLeft = "ScrollUp"
PaddleRight = "ScrollDown"

PinkyLeft = "Layer1" # Weapons

[layers.1] # Weapons
ActionH = "1" # Primary
ActionB = "2" # Secondary
ActionV = "3" # Mobilitty
ActionA = "4" # Utility
ActionC = "5" # Resupply
