# Deep Rock Galactic, with Flydigi Apex 2 in mind
game = "Deep Rock Galactic"

[mapping]
PovLeft = "A" # Primary Weapon
PovRight = "D" # Secondary Weapon
PovUp = "W" # Mobility Tool
PovDown = "S" # Utility Tool
CamX = { action = "FlickX" } # Turn
CamY = { action = "FlickY" } # Turn

BumperL = "Ctrl" # Laser Pointer
PinkyLeft = "Shift" # Sprint
ActionL = "Space" # Jump
ActionR = "E" # Interact

TriggerR = "M1" # Shoot
TriggerL = "M2" # Mine
BumperR = "G" # Grenade
ActionH = "R" # Reload
ActionB = "F" # Flares

JoyX = { action = "NegPos", keys = ["1", "2"], deadzone = 0.65 } # Primary, Secondary
JoyY = { action = "NegPos", keys = ["3", "4"], deadzone = 0.65 } # Mobility, Support
Joy = "5" # Resupply

MenuL = "Tab" # Map
MenuR = "Escape" # Pause

ActionV = "C" # Molly
ActionD = "V" # Salute
