# Deep Rock Galactic, with Flydigi Apex 2 in mind
game = "Deep Rock Galactic"
fps = 60 # How often to read/emit inputs
flick180 = 1560 # Mouse units to move 180

[mapping]
# Right Stick for turning (disable stick with steam input)
CamX = "FlickX" # Turn
CamY = "FlickY" # Turn

# Seperate reload and interact buttons (disable ActionH button with steam input)
ActionR = "E" # Interact
ActionH = "R" # Reload
ActionC = "5" # Resupply

# Alternate weapon selection so you can keep moving
PinkyLeft = "Layer1" # Weapons
[layers.1] # Weapons
ActionH = "1" # Primary
ActionB = "2" # Secondary
ActionV = "3" # Mobilitty
ActionA = "4" # Utility
