# Swat 4, with Flydigi Apex 2 in mind
game = "Swat 4"

[mapping]
PovLeft = "A" # Strafe Left
PovRight = "D" # Strafe right
PovUp = "W" # Walk
PovDown = "S" # Retreat
JoyX = { action = "NegPos", keys = ["Q", "E"] } # Lean Left/Right
CamX = "FlickX" # Turn
CamY = "FlickY" # Turn

PaddleLeft = "C" # Crouch
ActionL = "Shift" # Toggle sprint

TriggerR = "M1" # Shoot
TriggerL = "M2" # Hold for commands
BumperR = "X" # Toggle firing mode

ActionR = "F" # Use
ActionA = "R" # Reload
BumperL = "Z" # Zoom

MenuL = "M" # Show objectives
MenuR = "Escape" # Pause

ActionD = "Ctrl" # Prepare Command
PaddleRight = "Tab" # Cycle command group

ActionH = "Layer1" # Grenade selection
ActionV = "Layer2" # Door tools
ActionB = "Layer3" # Pacifying tools
ActionC = "Layer4" # Commands
PinkyLeft = "Layer5" # Weapons

[layers.1] # Grenade selection
CamX = { action = "NegPos", keys = ["3", "5"], deadzone = 0.65 } # Flash, Stinger
CamY = { action = "NegPos", keys = ["4", "4"], deadzone = 0.65 } # CS

[layers.2] # Door tools
CamX = { action = "NegPos", keys = ["8", "0"], deadzone = 0.65 } # Toolkit, Wedge
CamY = { action = "NegPos", keys = ["7", "9"], deadzone = 0.65 } # Breach, Optiwand

[layers.3] # Pacifying tools
CamX = { action = "NegPos", keys = ["6", "H"], deadzone = 0.65 } # Pepper / Handcuffs
CamY = { action = "NegPos", keys = ["6", "H"], deadzone = 0.65 } # Duplicated for diagonals

[layers.4] # Commands
BumperL = "Insert" # Cycle Red Team Viewport
BumperR = "Home" # Cycle Blue Team Viewport
ActionL = "PageUp" # Cycle Sniper Team Viewport
MenuL = "Backspace" # Control Active Viewport
ActionR = "Space" # Quick Command

[layers.5] # Weapons
ActionH = "1" # Primary
ActionB = "2" # Secondary
ActionV = "V" # Flashlight
ActionA = "L" # Light Stick
