# Swat 4, with Flydigi Apex 2 in mind
game = "Swat 4"

[mapping]
JoyX = ["A", "D"] # Strafe
JoyY = ["W", "S"] # Walk
# CamX = { action = "mouse", mousemode = 'flickstick', axis = "x" } # Turn
# CamY = { action = "mouse", mousemode = 'flickstick', axis = "y" } # Turn
CamX = { action = "mouse", mousemode = 'relative', axis = "x" } # Turn/Look
CamY = { action = "mouse", mousemode = 'relative', axis = "y" } # Look

BumperL = "Q" # Lean L
BumperR = "E" # Lean R
PaddleLeft = "C" # Crouch
PaddleRight = "Shift" # Toggle sprint

TriggerR = "M1" # Shoot
TriggerL = "M2" # Hold for commands
PinkyLeft = "X" # Toggle firing mode
PovLeft = "1" # Primary Weapon
PovRight = "2" # Secondary Weapon

ActionR = "F" # Use
ActionA = "R" # Reload
ActionL = "Z" # Zoom
ActionC = "V" # Flashlight

MenuL = "M" # Show objectives
MenuR = "Escape" # Pause

PovUp = "ScrollUp" # Select command up
PovDown = "ScrollDown" # Select command down
ActionD = "Space" # Quick command

ActionH = { layer = 1 } # Grenade selection
ActionV = { layer = 2 }
ActionB = { layer = 3 }

[layers.1.mapping] # Grenade selection with X+wheel
CamX = ["3", "5"] # Flash, Stinger
CamY = ["4", "4"] # CS

[layers.2.mapping] # Door tools
CamX = ["8", "0"] # Toolkit, Wedge
CamY = ["7", "9"] # Breach, Optiwand

[layers.3.mapping] # Pacifying tools
CamX = ["6", "H"] # Pepper / Handcuffs
CamY = ["6", "H"] # Duplicated for diagonals
