# World War Z, with Flydigi Apex 2 in mind
game = "World War Z"
fps = 60 # How often to read/emit inputs
flick180 = 5888 # Mouse units to move 180
flickDeadzone = 0.7

[mapping]
# D-Pad for digital movement
PovLeft = "A" # Strafe Left
PovRight = "D" # Strafe Right
PovUp = "W" # Walk
PovDown = "S" # Retreat

CamX = "FlickX" # Turn
CamY = "FlickY" # Turn

ActionL = "Shift" # Sprint
ActionA = "Space" # Jump
ActionB = "Ctrl" # Toggle crouch

TriggerR = "M1" # Fire
TriggerL = "M2" # Aim
ActionH = "R" # Reload
BumperL = "M3" # Equipment
BumperR = "F" # Melee
ActionR = "E" # Interact

ActionC = "T" # Mark Target
ActionD = "4" # Use medkit

MenuL = "Tab" # Scoreboard
MenuR = "Escape" # Pause

PinkyLeft = "Layer1" # Weapons

ActionV = "4" # Medkit
[layers.1] # Weapons
ActionH = "2" # Primary
ActionB = "1" # Secondary
ActionA = "3" # Heavy Weapon

ActionC = "Enter" # OK
ActionD = "Escape" # Cancel
